dataset: "cifar100"
num_classes: 100

use_amp: false
lr_name: "exponential"
initial_lr: 0.002
t_mul: 2.0
m_mul: 1.0
alpha: 1.0e-7
decay_epochs: 5.0
decay_rate: 0.5
warmup_epochs: 0
opt_name: "adamb"
decay: 0.9
epsilon: 1.0e-6
lookahead: 0
momentum: 0.9
moving_average_decay: 0.9999
weight_decay: 0.001
nesterov: false
beta_1: 0.9 
beta_2: 0.999
grad_clip_norm: 0
grad_accum_steps: 1
hvd_fp16_compression: false
intratrain_eval_using_ema: true
label_smoothing: 0.1 
